### ISSUE TITLE
templates: `bin` path prefix necessary for `importmap`

### ISSUE THREAD

**Issue by ybakos** [alexandreruban/rebuilding-turbo-rails#2]
Video "Testing our clone in a real Rails app", 6:05.

In *lib/install/turbo_with_importmap.rb*, perhaps the importmap command should have been:

```
run "bin/importmap pin @hotwired/turbo-rails@7.1.1"
```

Instead of:

```
run "importmap pin @hotwired/turbo-rails@7.1.1"
```

During a vanilla installation of the turbo_test Rails app, we need to lean on *bin/importmap* rather than a global executable. (Without the prefix, we get a "command not found" error.)

**Comment by alexandreruban** [comment]
Hello @ybakos,

Thanks a lot for your feedback 🙏. I always forget to add `bin/` before the rails commands because I have the following config in my `.zshrc`:

```sh
# Rails and Ruby uses the local `bin` folder to store binstubs.
# So instead of running `bin/rails` like the doc says, just run `rails`
# Same for `./node_modules/.bin` and nodejs
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"
```

I added a comment on this video.
